site_name: Artificial Intelligence, Programming and Robotics (I) - 2.º ESO
use_directory_urls: false
nav:
- 'Artificial Intelligence':
  - '0. Introduction to AI' : 'contents/ai/intro.md' 
#    - 'The Turing Test': 'contents/ai/the-turing-test.md'
#    - 'AI terms' : 'contents/ai/terms.md'
  #  - 'Activity 1. The Turing Test': 'contents/ai/activity-turing.md'  
  - '1. Learning: Biological Systems and AI':
    - 'Learning in Biological Systems: Decisions and Free Will': 'contents/ai/ai-bio.md'
    - 'Learning, AI, Programming, and Robots': 'contents/ai/learning-aipr.md'
  - '2. Sensors, typology and applications':
    - 'Sensors': 'contents/ai/Sensors.md'
    - 'Types of sensors': 'contents/ai/types-of-sensors.md'
    - 'Applications': 'contents/ai/sensors-applications.md'
  - '3. Fundamentals of AI':
    - 'Fundamentals of AI' : 'contents/ai/ai-fundamentals.md'
    - 'Decision Trees' : 'contents/ai/decision-trees.md'  
    - 'Big Data' : 'contents/ai/big-data.md'
    - 'Neural Networks' : 'contents/ai/neural-networks.md'
  - '4. Basic techniques of AI':
    - 'Expert systems' : 'contents/ai/expert-systems.md'
    - 'Neural networks' : 'contents/ai/neural-networks-tech.md'
    - 'Machine learning' : 'contents/ai/machine-learning.md'
  - '5. Automatic information processing':
    - 'Automatic information processing' : 'contents/ai/auto-inf-processing.md'
  - '6. Equity and inclusion in AI systems. Biases in AI':
    - 'Equity and inclusion in AI systems' : 'contents/ia/equity-inclusion.md'
    - 'Biases in AI' : 'contents/ia/biases-ai.md'
  - '7. Social and ethical implications of artificial intelligence':
    - 'Social and ethical implications of artificial intelligence': 'contents/ai/social-ethical-ai.md'
  - '8. Virtual reality techniques':
    - 'Virtual reality techniques': 'contents/ai/vr-techniques.md'
- 'Programming':
  - '0. Introduction to Programming' : 'contents/programming/intro.md' 
  - '1. Interpretation of reality through problem modeling': 'contents/programming/problem-modeling.md'
  - '2. Abstraction, sequencing, algorithmic and its representation with natural language and flow diagrams':
    - 'Introduction' : 'contents/ai/abstraction.md'
  - '3. Pattern detection and reuse. Generalization':
    - 'Item'
  - '4. Sustainability and inclusion as software design requirements':
    - 'Item'
  - '5. Program flow control structures':
    - 'Item'
  - '6. Variables, constants, conditions and operators':
    - 'Item'
  - '7. Introduction to programming in high-level languages. Types of languages. Syntax and semantics':
    - 'Item'
  - '8. Mobile device application programming':
    - 'Item'
  - '9. Software evaluation and maintenance':
    - 'Item'
  - '10. Software licenses. Free software and proprietary software':
    - 'Item'
  - '11. Controller card simulators':
    - 'Item'
  - '12. Initiative, self-confidence and metacognition in the software development learning process':
    - 'Item'
  - 'Project Rock Paper Scissors Lizard Spock':
    - '0. The Project' : 'contents/programming/rpsls/project.md'
    - '1. The Game' : 'contents/programming/rpsls/thegame.md'
    - '2. Graphics and Animation' : 'contents/programming/rpsls/animation.md'
    - '3. Logic and Flow Control' : 'contents/programming/rpsls/logic.md'
    - '4. Final Version and Testing' : 'contents/programming/rpsls/final.md'
    - 'Tutorial: Rock, Paper, Scissors' : 'contents/programming/rpsls/rps_tutorial.md'

- 'Robotics':
  - '0. Introduction to Robotics' :
    - 'Introduction' : 'contents/robotics/intro.md' 
    - 'What is a robot?' : 'contents/robotics/robots.md'
    - 'Robots and AI' : 'contents/robotics/robots_ai.md'
    - 'Robots' : 'contents/robotics/crashcourse_robots.md'
    - 'Robotics and AI' : 'contents/robotics/crashcourse_robotics_ai.md'
    - 'How Engineering Robots Works' : 'contents/robotics/crashcourse_robots_engineering.md'
  - '1. Robots: Types, Degrees of Freedom, and Basic Technical Characteristics':
    - 'Item' : 'contents/robotics/item.md'  
  - '2. Robot assembly':
    - 'Item'
  - '3. Control of robotic systems':
    - 'Introduction to mBlock' : 'contents/robotics/mblock.md'
  - '4. Sensors, actuators and controllers':
    - 'Introduction' : 'contents/robotics/intro_sens_act_contr.md'
    - 'Sensors' : 'contents/robotics/sensors.md'
    - 'Actuators' : 'contents/robotics/actuators.md'
    - 'Controllers' : 'contents/robotics/controllers.md'
    - 'mBot' : 'contents/robotics/mbot.md'
  - '5. Loading and execution of algorithms in robots':
    - 'Item'
  - '6. Robotic systems in experimentation with designed prototypes':
    - 'Item'
  - 'Project (I): Robot Research' : 'contents/robotics/robotresearch.md'
  - 'Project (II): mBot Robot Programming' : 'contents/robotics/mbotcode.md'
#- 'Programación Didáctica':
#    - 'Elementos curriculares': 'pd/curriculo/curriculo.md'
- 'More':
  - 'Blog': 'https://www.esferatic.com'
  - 'Instagram': 'https://www.instagram.com/esferatic'

theme:
    language: es
    name: 'readthedocs'
    palette:
        primary: 'Teal'
        accent: 'Teal'
    font:
        text: Roboto
        code: Roboto Mono
    logo: 'images/floppy-ict2.png'

plugins:
  - glightbox
  - search
  - mermaid2
  #- pandoc
  #pandoc:
  # - combined: true

markdown_extensions:
  - attr_list
  - sane_lists
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_css:
  - css/ict.css

extra_javascript:
  - https://unpkg.com/mermaid@10.2.4/dist/mermaid.min.js